sudo: false
language: java
script: boot test-code
install:
  - mkdir -p ~/bin
  - export PATH=~/bin:$PATH
  # Could use `latest` tag instead of version number
  - curl -L https://github.com/boot-clj/boot-bin/releases/download/2.5.2/boot.sh -o ~/bin/boot
  - chmod +x ~/bin/boot
env:
  matrix:
    # Runs tests twice, using Clj 1.7 and 1.8
    - BOOT_CLOJURE_VERSION=1.7.0
    - BOOT_CLOJURE_VERSION=1.8.0
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.boot/cache/bin
  - $HOME/.boot/cache/lib
  - $HOME/bin